### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by waywtdcc** [shouxieai/minio-cpp-sdk#1]
Downloaded is the master branch code. When I run make run -j6, an error is reported. The error is displayed as follows

`
Compile CXX src/minio_client.cpp
In file included from /home/aicore/compile_test/extra_library/openssl-1.1.1l/include/openssl/evp.h:16:0,
                 from /home/aicore/compile_test/extra_library/openssl-1.1.1l/include/openssl/hmac.h:15,
                 from src/minio_client.cpp:3:
/home/aicore/compile_test/extra_library/openssl-1.1.1l/include/openssl/bio.h:687:1: 错误：expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_1_1_0’
 DEPRECATEDIN_1_1_0(int BIO_get_port(const char *str, unsigned short *port_ptr))
 ^
In file included from /home/aicore/compile_test/extra_library/openssl-1.1.1l/include/openssl/asn1.h:23:0,
                 from /home/aicore/compile_test/extra_library/openssl-1.1.1l/include/openssl/objects.h:15,
                 from /home/aicore/compile_test/extra_library/openssl-1.1.1l/include/openssl/evp.h:28,
                 from /home/aicore/compile_test/extra_library/openssl-1.1.1l/include/openssl/hmac.h:15,
                 from src/minio_client.cpp:3:
/home/aicore/compile_test/extra_library/openssl-1.1.1l/include/openssl/bn.h:332:1: 错误：expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_0_9_8’
 DEPRECATEDIN_0_9_8(int
 ^
/home/aicore/compile_test/extra_library/openssl-1.1.1l/include/openssl/bn.h:403:1: 错误：expected constructor, destructor, or type conversion before ‘DEPRECATEDIN_0_9_8’
 DEPRECATEDIN_0_9_8(int BN_get_params(int which)) /* 0, mul, 1 high, 2 low, 3
 ^
In file included from /home/aicore/compile_test/extra_library/openssl-1.1.1l/include/openssl/objects.h:15:0,
                 from /home/aicore/compile_test/extra_library/openssl-1.1.1l/include/openssl/evp.h:28,
                 from /home/aicore/compile_test/extra_library/openssl-1.1.1l/include/openssl/hmac.h:15,
                 from src/minio_client.cpp:3:
/home/aicore/compile_test/extra_library/openssl-1.1.1l/include/openssl/asn1.h:555:7: 错误：expected constructor, destructor, or type conversion before ‘unsigned’
 const unsigned char *ASN1_STRING_get0_data(const ASN1_STRING *x);
       ^
In file included from src/minio_client.cpp:3:0:
/home/aicore/compile_test/extra_library/openssl-1.1.1l/include/openssl/hmac.h:33:12: 错误：expected constructor, destructor, or type conversion before ‘int’
 /*__owur*/ int HMAC_Init_ex(HMAC_CTX *ctx, const void *key, int len,
            ^
src/minio_client.cpp: 在函数‘std::string hmac_encode_base64(const string&, const void*, size_t)’中:
src/minio_client.cpp:60:63: 错误：‘HMAC_Init_ex’在此作用域中尚未声明
     HMAC_Init_ex(ctx, key.data(), key.size(), EVP_sha1(), NULL);

`

makefile content is

`
cpp_srcs := $(shell find src -name "*.cpp")
cpp_objs := $(patsubst %.cpp,%.o,$(cpp_srcs))
cpp_objs := $(subst src/,objs/,$(cpp_objs))

openssl_path := /home/aicore/compile_test/extra_library/openssl-1.1.1l
curl_path    := /home/aicore/compile_test/extra_library/curl-7.77.0

include_paths := src \
			$(openssl_path)/include \
			$(curl_path)/include

library_paths := \
			$(openssl_path)/lib \
			$(curl_path)/lib

link_librarys := ssl crypto curl stdc++ dl

run_paths     := $(foreach item,$(library_paths),-Wl,-rpath=$(item))
include_paths := $(foreach item,$(include_paths),-I$(item))
library_paths := $(foreach item,$(library_paths),-L$(item))
link_librarys := $(foreach item,$(link_librarys),-l$(item))

cpp_compile_flags := -std=c++11 -fPIC -m64 -g -fopenmp -w -O0
link_flags        := -pthread -fopenmp

cpp_compile_flags += $(include_paths)
link_flags 		  += $(library_paths) $(link_librarys) $(run_paths)

pro : workspace/pro

workspace/pro : $(cpp_objs)
	@echo Link $@
	@mkdir -p $(dir $@)
	@g++ $^ -o $@ $(link_flags)

objs/%.o : src/%.cpp
	@echo Compile CXX $<
	@mkdir -p $(dir $@)
	@g++ -c $< -o $@ $(cpp_compile_flags)

run : workspace/pro
	@cd workspace && ./pro

clean :
	@rm -rf objs workspace/pro

.PHONY : clean pro run

`

**Comment by shouxieai** [comment]
你可能要确认你的编译器gcc版本是否能够正确使用openssl。这是openssl的报错
